//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewerIntegration {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class ViewerIntegrationSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ViewerIntegrationSettings defaultInstance = ((ViewerIntegrationSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ViewerIntegrationSettings())));
        
        public static ViewerIntegrationSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\ClearCanvas\\ClearCanvas Workstation")]
        public string ViewerWorkingDirectory {
            get {
                return ((string)(this["ViewerWorkingDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ClearCanvas.Desktop.Executable")]
        public string ViewerProcessExecutable {
            get {
                return ((string)(this["ViewerProcessExecutable"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DicomAEServers.xml")]
        public string ViewerDicomAEServersFile {
            get {
                return ((string)(this["ViewerDicomAEServersFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ViewerReachableNumberOfAttempts {
            get {
                return ((int)(this["ViewerReachableNumberOfAttempts"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int ViewerReachableDelayAttempsInMilliSeconds {
            get {
                return ((int)(this["ViewerReachableDelayAttempsInMilliSeconds"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IVO")]
        public string MoveScuLocalAe {
            get {
                return ((string)(this["MoveScuLocalAe"]));
            }
        }
    }
}
